// ─────────────────────────────────────────────────────────────────────────
// The fal.ai image-generation seam.
//
// If FAL_KEY is present in the SERVER env, we call fal.ai for real:
//   fal.config({ credentials: process.env.FAL_KEY })
//   await fal.subscribe(MODEL, { input: { prompt, image_size, num_images: 1,
//     num_inference_steps: 28, guidance_scale: 5 } })
//   → result.data.images[0].url → fetch the bytes → write to disk.
//
// If FAL_KEY is ABSENT, we fall back to a deterministic STUB that writes a
// warm-sand placeholder JPEG. Everything works offline, and the public repo is
// safe: the secret only ever lives in .env.local (gitignored) and is read from
// process.env here. It is NEVER logged, returned, or written to disk.
//
// MODEL defaults to "fal-ai/nano-banana-pro", overridable via FAL_MODEL.
// ─────────────────────────────────────────────────────────────────────────

import { promises as fs } from "node:fs";
import path from "node:path";

import { fal } from "@fal-ai/client";

import type { ImageSizePreset } from "./prompt";

const DEFAULT_MODEL = "fal-ai/nano-banana-pro";
const NUM_INFERENCE_STEPS = 28;
const GUIDANCE_SCALE = 5;

/** Result of generating one image: its public path and how it was made. */
export interface RenderedImage {
  /** Absolute path written on disk. */
  absolutePath: string;
  /** Public URL the app serves it at (e.g. /images/products/foo-01.jpg). */
  publicPath: string;
  /** "fal" when generated by fal.ai, "stub" when the offline placeholder ran. */
  source: "fal" | "stub";
}

/** Is a real fal credential present in the server env? */
export function hasFalKey(): boolean {
  return Boolean(process.env.FAL_KEY && process.env.FAL_KEY.trim());
}

function modelId(): string {
  const m = process.env.FAL_MODEL?.trim();
  return m && m.length > 0 ? m : DEFAULT_MODEL;
}

// The fal client expects a specific union for image_size; map our presets.
type FalImageSize =
  | "landscape_16_9"
  | "landscape_4_3"
  | "portrait_4_3"
  | "portrait_16_9"
  | "square";

function toFalImageSize(preset: ImageSizePreset): FalImageSize {
  return preset;
}

// Narrow shape of the fal subscribe result we depend on. We avoid `any` by
// validating the shape at runtime instead of casting blindly.
interface FalImage {
  url: string;
}
function firstImageUrl(data: unknown): string | null {
  if (typeof data !== "object" || data === null) return null;
  const images = (data as { images?: unknown }).images;
  if (!Array.isArray(images) || images.length === 0) return null;
  const first = images[0] as Partial<FalImage>;
  return typeof first?.url === "string" ? first.url : null;
}

/**
 * Generate one image for `prompt` and write it to `absolutePath`. Returns the
 * rendered descriptor. Falls back to the deterministic stub when no FAL_KEY is
 * set, or if a real call fails (so the Studio never hard-fails on a flaky API).
 */
export async function renderImage(args: {
  prompt: string;
  imageSize: ImageSizePreset;
  absolutePath: string;
  publicPath: string;
  /** Seed used by the stub for deterministic placeholder variation. */
  stubSeed: number;
}): Promise<RenderedImage> {
  await fs.mkdir(path.dirname(args.absolutePath), { recursive: true });

  if (!hasFalKey()) {
    await writeStub(args.absolutePath, args.imageSize, args.stubSeed);
    return {
      absolutePath: args.absolutePath,
      publicPath: args.publicPath,
      source: "stub",
    };
  }

  try {
    // Configure with the secret read from the server env. Never logged.
    fal.config({ credentials: process.env.FAL_KEY });

    const result = await fal.subscribe(modelId(), {
      input: {
        prompt: args.prompt,
        image_size: toFalImageSize(args.imageSize),
        num_images: 1,
        num_inference_steps: NUM_INFERENCE_STEPS,
        guidance_scale: GUIDANCE_SCALE,
      },
    });

    const url = firstImageUrl((result as { data?: unknown }).data);
    if (!url) {
      throw new Error("fal returned no image url");
    }

    const res = await fetch(url);
    if (!res.ok) {
      throw new Error(`fetch image failed (${res.status})`);
    }
    const bytes = Buffer.from(await res.arrayBuffer());
    await fs.writeFile(args.absolutePath, bytes);

    return {
      absolutePath: args.absolutePath,
      publicPath: args.publicPath,
      source: "fal",
    };
  } catch {
    // Degrade gracefully to the stub. We intentionally swallow the error detail
    // here so nothing about the credential or upstream response can leak.
    await writeStub(args.absolutePath, args.imageSize, args.stubSeed);
    return {
      absolutePath: args.absolutePath,
      publicPath: args.publicPath,
      source: "stub",
    };
  }
}

// ── Deterministic warm-sand placeholder JPEG ────────────────────────────────
// We synthesize a tiny, valid baseline JPEG entirely from bytes — no native
// deps, no canvas — so it works in any Node runtime, online or off. The image
// is a single warm-sand chroma block; the seed nudges the luma so variants
// differ visibly. It is intentionally low-res (it's a placeholder).

const SAND_PRESETS: ReadonlyArray<{ y: number; cb: number; cr: number }> = [
  { y: 0xd8, cb: 0x76, cr: 0x8e }, // warm sand
  { y: 0xc9, cb: 0x72, cr: 0x96 }, // clay
  { y: 0xb8, cb: 0x7c, cr: 0x88 }, // stone
  { y: 0x3a, cb: 0x80, cr: 0x80 }, // sumi (dark)
];

async function writeStub(
  absolutePath: string,
  imageSize: ImageSizePreset,
  seed: number,
): Promise<void> {
  const portrait = imageSize.startsWith("portrait");
  const w = portrait ? 24 : 32;
  const h = portrait ? 32 : 24;
  const tone = SAND_PRESETS[Math.abs(seed) % SAND_PRESETS.length];
  const jpeg = buildSolidJpeg(w, h, tone.y, tone.cb, tone.cr);
  await fs.writeFile(absolutePath, jpeg);
}

/**
 * Build a minimal valid baseline-DCT JPEG of a single solid YCbCr color.
 * Uses the canonical example Huffman/quant tables; every 8x8 MCU encodes only
 * a DC coefficient (the solid tone), AC all-zero. Small but spec-valid.
 */
function buildSolidJpeg(
  width: number,
  height: number,
  y: number,
  cb: number,
  cr: number,
): Buffer {
  const ZIGZAG_QT = new Uint8Array(64).fill(16); // flat quant table (q≈medium)

  // Standard JPEG luminance/chrominance Huffman tables (Annex K).
  const STD_DC_LUM_BITS = [0, 1, 5, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0];
  const STD_DC_LUM_VALS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11];

  const out: number[] = [];
  const push = (...bytes: number[]) => out.push(...bytes);
  const push16 = (n: number) => out.push((n >> 8) & 0xff, n & 0xff);

  // SOI
  push(0xff, 0xd8);

  // APP0 / JFIF
  push(0xff, 0xe0);
  push16(16);
  push(0x4a, 0x46, 0x49, 0x46, 0x00); // "JFIF\0"
  push(1, 1); // version 1.1
  push(0); // units
  push16(1);
  push16(1); // density
  push(0, 0); // thumbnail

  // DQT (one table, id 0)
  push(0xff, 0xdb);
  push16(67);
  push(0x00);
  for (let i = 0; i < 64; i++) push(ZIGZAG_QT[i]);

  // SOF0 (baseline), 3 components, all using qt 0, no subsampling (1x1)
  push(0xff, 0xc0);
  push16(17);
  push(8); // precision
  push16(height);
  push16(width);
  push(3); // components
  push(1, 0x11, 0); // Y: id1, 1x1, qt0
  push(2, 0x11, 0); // Cb
  push(3, 0x11, 0); // Cr

  // DHT — define one DC + one AC table, reused for all components. To keep this
  // self-contained we encode every coefficient with a literal bit-emitter
  // (below) and only need a DC table whose codes we control. We emit a single
  // DC table (id 0) and a trivial AC table (id 0) with an EOB code of length 2.
  // DC table 0
  push(0xff, 0xc4);
  {
    const len = 2 + 1 + 16 + STD_DC_LUM_VALS.length;
    push16(len);
    push(0x00); // class 0 (DC), id 0
    for (const b of STD_DC_LUM_BITS) push(b);
    for (const v of STD_DC_LUM_VALS) push(v);
  }
  // AC table 0 — single symbol 0x00 (EOB) with a 2-bit code "00".
  push(0xff, 0xc4);
  {
    const acBits = [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    const acVals = [0x00];
    const len = 2 + 1 + 16 + acVals.length;
    push16(len);
    push(0x10); // class 1 (AC), id 0
    for (const b of acBits) push(b);
    for (const v of acVals) push(v);
  }

  // SOS — 3 components, each DC table 0 / AC table 0
  push(0xff, 0xda);
  push16(12);
  push(3);
  push(1, 0x00);
  push(2, 0x00);
  push(3, 0x00);
  push(0, 63, 0); // spectral start/end, ah/al

  // ── Entropy-coded data ────────────────────────────────────────────────
  // For each 8x8 block we emit: DC diff (category + bits) then AC EOB.
  // DC category codes from STD_DC table: code for category k is k bits long
  // following the standard table; we use the helper below.
  const bitBuf: number[] = [];
  let bitCount = 0;
  let cur = 0;
  const writeBits = (value: number, length: number) => {
    for (let i = length - 1; i >= 0; i--) {
      cur = (cur << 1) | ((value >> i) & 1);
      bitCount++;
      if (bitCount === 8) {
        bitBuf.push(cur);
        if (cur === 0xff) bitBuf.push(0x00); // byte-stuff
        cur = 0;
        bitCount = 0;
      }
    }
  };

  // Standard DC luminance Huffman codes (category → {code, length}).
  const DC_CODES: ReadonlyArray<{ code: number; len: number }> = [
    { code: 0x00, len: 2 }, // 0
    { code: 0x02, len: 3 }, // 1
    { code: 0x03, len: 3 }, // 2
    { code: 0x04, len: 3 }, // 3
    { code: 0x05, len: 3 }, // 4
    { code: 0x06, len: 3 }, // 5
    { code: 0x0e, len: 4 }, // 6
    { code: 0x1e, len: 5 }, // 7
    { code: 0x3e, len: 6 }, // 8
    { code: 0x7e, len: 7 }, // 9
    { code: 0xfe, len: 8 }, // 10
    { code: 0x1fe, len: 9 }, // 11
  ];

  // Encode a DC value (already level-shifted, divided by quant): emit category
  // code then the value bits. We encode the full level on the FIRST block of a
  // component and 0-diff afterward (all blocks share the same tone).
  const encodeDc = (diff: number) => {
    const cat = diff === 0 ? 0 : Math.floor(Math.log2(Math.abs(diff))) + 1;
    const c = DC_CODES[cat];
    writeBits(c.code, c.len);
    if (cat > 0) {
      const v = diff < 0 ? diff + (1 << cat) - 1 : diff;
      writeBits(v, cat);
    }
  };
  const encodeAcEob = () => writeBits(0x00, 2); // EOB code "00"

  // Level-shift (−128) then quantize by 16 to get the DC coefficient.
  const dcOf = (sample: number) => Math.round((sample - 128) / 16);
  const yDc = dcOf(y);
  const cbDc = dcOf(cb);
  const crDc = dcOf(cr);

  const blocksW = Math.ceil(width / 8);
  const blocksH = Math.ceil(height / 8);
  const totalBlocks = blocksW * blocksH;

  for (let i = 0; i < totalBlocks; i++) {
    // Interleaved MCU: Y, Cb, Cr (all 1x1). First MCU carries the full DC; the
    // rest carry a 0 diff because the tone is constant.
    encodeDc(i === 0 ? yDc : 0);
    encodeAcEob();
    encodeDc(i === 0 ? cbDc : 0);
    encodeAcEob();
    encodeDc(i === 0 ? crDc : 0);
    encodeAcEob();
  }

  // Flush remaining bits, padded with 1s.
  if (bitCount > 0) {
    cur = (cur << (8 - bitCount)) | ((1 << (8 - bitCount)) - 1);
    bitBuf.push(cur);
    if (cur === 0xff) bitBuf.push(0x00);
  }
  for (const b of bitBuf) push(b);

  // EOI
  push(0xff, 0xd9);

  return Buffer.from(out);
}
